---
title: "Intro to Data Vis HW 2"
output: html_notebook
---

```{r setup}
knitr::opts_chunk$set(fig.width = 20, fig.height = 17)

require(data.table)
require(magrittr)
require(tidyverse)
require(ggthemes)
require(ggthemr)
require(corrr)
require(VIM)
require(h2o)

# Initialize h2o
h2o.init()
```

```{r load data}
home_train <- fread("../data/train.csv")
home_test <- fread("../data/test.csv")  # Missing response - used for Kaggle submission

names(home_train)
# Remove id column from home_train
home_train[,Id := NULL]
```


## Introduction
## EDA
```{r}
# Number of discrete and continuous features
sapply(home_train, class) %>% 
  table

# Define dependent variable
y <- "SalePrice"

# Extract names of continuous features
cont_features <- names(home_train)[sapply(home_train, class) == "integer"]
cont_features <- setdiff(cont_features, y)

# Extract names of discrete features
disc_features <- names(home_train)[sapply(home_train, class) == "character"]

# Explore missingness of data
aggr(home_train[,-y, with = FALSE])
```

```{r discrete features}
# Count of distinct values in each discrete feature
home_train[,disc_features, with = FALSE] %>% 
  melt(measure.vars = disc_features) %>% 
  ggplot(aes(x = value)) +
  geom_bar(na.rm = FALSE) +
  facet_wrap(~variable, scales = "free") +
  theme_tufte() +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 45))

# Boxplot of response variable for discrete features
give_n <- function(x){ return(c(ymin = median, label = length(x))) }

home_train[,c(disc_features, y), with = FALSE] %>% 
  melt(measure.vars = disc_features) %>% 
  ggplot(aes(x = value, y = SalePrice)) +
  geom_boxplot() +
  # stat_summary(fun.data = give_n, geom = "text", fun.y= median) +
  facet_wrap(~variable, scales = "free") +
  theme_tufte() +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 45))
```

```{r}
# Explore sparse variables
home_train[,.N, by = .(Alley, Street)]
home_test[,.N, by = Utilities]
home_train[,.N, by = Alley]
home_train %>% 
  ggplot(aes(x = MiscFeature)) +
  geom_bar() +
  theme_minimal()

# Explore variables of high missingness
home_train[,summary(PoolArea)]
home_train[PoolArea != 0, .(.N, mean(SalePrice)), by = PoolQC]
```


```{r continuous features}
# Correlation matrix
house_corplot <- home_train[,c(cont_features, y), with = FALSE] %>% 
  correlate %>% 
  rearrange() %>% 
  shave() %>% 
  rplot()
  
house_corplot +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```




## Feature Engineering
## Data Modeling
Limited number of observations. Cross validation will be used to maximize training potential.
```{r h2o setup}

```

## Kaggle Submission

